#!/usr/bin/env bash

echo "Usage: remove-red <java files>"
echo ""

for afile in $@
do
  echo "Remove red in file: $afile"
  cp $afile $afile.org
  # sed -E -i .bak "s/[[:space:]]+$//g" $afile
  # sed -E -i .bak "s/	/    /g" $afile
  sed -E -i '' "s/[[:space:]]+$//g" $afile
  sed -E -i '' "s/	/    /g" $afile
done
